### ISSUE TITLE
ReferenceError: ga is not defined

### ISSUE THREAD

**Issue by prog1dev** [MahdiF/taptaptap#4]
Circles don't change position on successful hit. In other words sub-level doesnt change

Error in console:
```
habibiScript.js:455 Uncaught ReferenceError: ga is not defined
```
[Here is a screenshot](https://imgur.com/a/TQvMl)

Browser: Chrome 64.0.3282.119

Works fine in Safari 11.0.3

**Comment by MahdiF** [comment]
This is happening because your browser is blocking Google analytics and I call a function to record the events when a circle is being clicked. I've just removed that function, and the game should work fine now.
Please let me know if it's still not working

**Comment by prog1dev** [comment]
it's working now 👍
